const courses=[
{id:1,title:"Fundamentals of Weather Forecasting",desc:"Core principles of synoptic analysis, observation and forecast interpretation.",trainer:"Dr. Ananya Sharma",level:"Intermediate",duration:"6 weeks",skills:["Forecast Analysis","Synoptic Analysis"],progress:68,learners:128},
{id:2,title:"Advanced Climate Data Analysis",desc:"Practical methods for interpreting climate datasets, anomalies and operational data.",trainer:"Dr. R. Menon",level:"Advanced",duration:"4 weeks",skills:["Data Analysis","Python"],progress:42,learners:96},
{id:3,title:"Meteorological Observation",desc:"Observation practices, instruments and quality assurance fundamentals.",trainer:"K. Das",level:"Beginner",duration:"3 weeks",skills:["Observation","Quality Control"],progress:100,learners:74},
{id:4,title:"Satellite Meteorology",desc:"Foundations of satellite imagery, products and interpretation.",trainer:"S. Iyer",level:"Advanced",duration:"5 weeks",skills:["Satellite Data","Image Interpretation"],progress:0,learners:63},
{id:5,title:"Disaster Risk Reduction",desc:"Capacity building for risk assessment, preparedness and response.",trainer:"M. Choudhury",level:"Intermediate",duration:"3 weeks",skills:["Risk Assessment","Preparedness"],progress:0,learners:112}
];
const competencies=[
["Forecast Analysis","Advanced","Verified",90],["Meteorological Observation","Advanced","Verified",88],
["Weather Data Interpretation","Intermediate","Verified",71],["Radar Analysis","Beginner","Gap",42],
["Data Analysis","Intermediate","Verified",62],["Python","Advanced","Verified",86],["GIS","Beginner","Needs Review",45]
];
const trainerMatches=[
{name:"Dr. Ananya Sharma",expertise:"Forecast Analysis · Radar Interpretation · Synoptic Meteorology",match:94,verified:true,course:"Fundamentals of Weather Forecasting"},
{name:"Dr. R. Menon",expertise:"Climate Data · Python · Data Analysis",match:89,verified:true,course:"Advanced Climate Data Analysis"},
{name:"S. Iyer",expertise:"Satellite Data · Image Interpretation",match:82,verified:true,course:"Satellite Meteorology"}
];
const qs=[
["Which parameter is most directly used to describe atmospheric pressure?",["Temperature","Pressure","Humidity","Visibility"],1],
["Which instrument is commonly used to measure air temperature?",["Barometer","Thermometer","Anemometer","Rain gauge"],1],
["Which observation helps describe wind direction?",["Wind vane","Hygrometer","Pyranometer","Seismometer"],0],
["Which skill is directly associated with interpreting radar products?",["Radar Analysis","Typing","Accounting","Procurement"],0]
];
let state={role:null,page:"Dashboard",signupStep:1,assessment:0,answers:{},assessmentDone:false,noticeCount:3,profileSaved:false,verifiedEvidence:false};
const traineeNav=["Dashboard","My Profile","Competency Assessment","Competency Profile","Skill Gaps","Recommended Learning","Trainer Matching","Course Catalogue","My Learning","Learning Resources","Assessments","Certificates","Feedback","Notifications","Settings","System Architecture"];
const trainerNav=["Dashboard","My Profile","My Courses","Create Course","Questionnaires","Assessments","Assigned Trainees","Trainee Performance","Trainer Library","Competency Mapping","Notifications","Settings","System Architecture"];
const adminNav=["Dashboard","User Approval","User Management","Role Management","Course Management","Enrollment Monitoring","Certification Monitoring","Assessment Monitoring","Participation Statistics","Competency Framework","Competency Mapping","Announcements","Achievements","Learning Content","Reports","Settings","System Architecture"];
const icons={"Dashboard":"▦","My Profile":"◯","Competency Assessment":"✓","Competency Profile":"◎","Skill Gaps":"⌕","Recommended Learning":"▤","Trainer Matching":"◌","Course Catalogue":"▥","My Learning":"▶","Learning Resources":"▤","Assessments":"✓","Certificates":"◇","Feedback":"✎","Notifications":"●","Settings":"⚙","My Courses":"▥","Create Course":"+","Questionnaires":"☑","Assigned Trainees":"♙","Trainee Performance":"▥","Trainer Library":"▤","Competency Mapping":"◌","User Approval":"✓","User Management":"♙","Role Management":"⇄","Course Management":"▦","Enrollment Monitoring":"↔","Certification Monitoring":"◇","Assessment Monitoring":"✓","Participation Statistics":"▥","Competency Framework":"◎","Announcements":"▰","Achievements":"★","Learning Content":"▤","Reports":"▧","System Architecture":"⌘"};

function toast(x){ return; } // UI alerts/toasts disabled by design
function openModal(content){document.getElementById("modal").innerHTML=`<div class="modalbox">${content}<div style="text-align:right;margin-top:16px"><button class="btn" onclick="closeModal()">Close</button></div></div>`;document.getElementById("modal").classList.add("show")}
function closeModal(){document.getElementById("modal").classList.remove("show")}
function nav(){return state.role==="Trainee"?traineeNav:state.role==="Trainer"?trainerNav:adminNav}
function saveView(){location.hash=state.role?encodeURIComponent(state.role)+"/"+encodeURIComponent(state.page):"landing"}
function go(p){state.page=p;persist();saveView();render();window.scrollTo({top:0,behavior:"smooth"})}
function logout(){state.role=null;state.page="Dashboard";persist();saveView();render();toast("Signed out of the demo session")}
function demoLogin(role){state.role=role;state.page="Dashboard";persist();saveView();render();toast(role+" demo session started")}
function help(){openModal(`<h2>Help & Support</h2><p class="muted">CAPACITY CONNECT demonstration support.</p><div class="notice"><b>Prototype note</b><br>This is a functional front-end demonstration. Flask REST API, MySQL and S3-compatible storage are the proposed production architecture.</div><p>For a production deployment, authentication, RBAC, evidence verification, competency rules and storage would be connected to the backend.</p>`)}
function shell(content){
const unread=state.noticeCount||0;
return `<header class="topbar"><button class="iconbtn mobile-toggle" aria-label="Open navigation" onclick="toggleSide()">☰</button><div class="brand"><div class="mark">CC</div><div><b>CAPACITY CONNECT</b><small>Digital Capacity Building & Learning Management Portal</small></div></div><div class="search"><span>⌕</span><input aria-label="Search" placeholder="Search courses, trainers, skills..." onkeydown="if(event.key==='Enter')toast('Search results prepared for: '+this.value)"></div><div class="top-actions"><button class="iconbtn" aria-label="Notifications" onclick="go('Notifications')">●${unread?`<span class="notif-dot">${unread>9?'9+':unread}</span>`:''}</button><button class="iconbtn" aria-label="Help and support" onclick="help()">?</button><div class="avatar" title="${state.role} profile">${state.role[0]}</div><button class="btn small" onclick="logout()">Logout</button></div></header><div class="layout"><aside class="sidebar"><div class="side-title">${state.role} Workspace</div>${nav().map(x=>`<a class="nav ${state.page===x?'active':''}" href="#" onclick="go('${x}');return false"><span class="nav-icon">${icons[x]||"•"}</span><span>${x}</span></a>`).join("")}</aside><main class="main">${content}<footer style="margin-top:35px;padding:18px 0;border-top:1px solid var(--line);color:var(--muted);font-size:11px;text-align:center">CAPACITY CONNECT · SIH 2026 · Prototype for SIH26075 · Accessibility · Privacy · Terms · Help & Support · Contact</footer></main></div>`
}
function page(title,sub,body,action=""){return body}
function kpi(label,value,trend="",kind=""){return `<div class="card kpi ${kind}"><div class="kpi-icon">${icons[label]||"•"}</div><div class="label">${label}</div><div class="value">${value}</div><div class="trend">${trend}</div></div>`}

function landing(){
return `<div style="min-height:100vh"><header class="topbar"><div class="brand"><div class="mark">CC</div><div><b>CAPACITY CONNECT</b><small>Digital Capacity Building & Learning Management Portal</small></div></div><div class="top-actions"><button class="btn" onclick="signup()">Register</button><button class="btn primary" onclick="loginView()">Login</button></div></header><section class="hero"><div><div class="eyebrow">SMART INDIA HACKATHON 2026 · SIH26075 · SMART EDUCATION</div><h1>CAPACITY<br>CONNECT</h1><h2>Digital Capacity Building & Learning Management Portal</h2><p>A centralized platform for organizational learning, competency development, training and knowledge sharing. Connect professional profiles, verified evidence, skill gaps, relevant learning and suitable trainers in one competency-driven workflow.</p><div class="hero-actions"><button class="btn primary" onclick="loginView()">Login</button><button class="btn" onclick="signup()">Register</button></div><div class="row" style="margin-top:17px"><span class="pill blue">Trainee</span><span class="pill blue">Trainer</span><span class="pill blue">Admin</span><span class="muted" style="font-size:11px">MoES / IMD context · DEMO data</span></div></div><div class="preview journey-preview"><div class="preview-top"><span class="dot"></span><span class="dot"></span><span class="dot"></span><span style="margin-left:auto;font-size:10px;color:#98a2b3">CAPACITY-BUILDING WORKFLOW</span></div><div class="journey-preview-body"><div class="journey-preview-intro"><span class="pill blue">COMPETENCY-DRIVEN</span><h3>From identifying a need to building verified capability.</h3><p>One connected workflow brings together profiles, competency assessment, learning and trainer support.</p></div><div class="journey-preview-flow"><div class="journey-preview-step active"><span>01</span><b>Profile</b><small>Build your capability profile</small></div><div class="journey-preview-connector"></div><div class="journey-preview-step"><span>02</span><b>Assess</b><small>Measure current competencies</small></div><div class="journey-preview-connector"></div><div class="journey-preview-step highlight"><span>03</span><b>Identify Gap</b><small>Find development priorities</small></div><div class="journey-preview-connector"></div><div class="journey-preview-step"><span>04</span><b>Learn</b><small>Get relevant learning paths</small></div><div class="journey-preview-connector"></div><div class="journey-preview-step"><span>05</span><b>Connect</b><small>Match with suitable trainers</small></div><div class="journey-preview-connector"></div><div class="journey-preview-step"><span>06</span><b>Verify</b><small>Demonstrate developed capability</small></div></div><div class="journey-preview-footer"><span>TRAINEE</span><span>TRAINER</span><span>ADMIN</span><b>One shared learning ecosystem</b></div></div></div></section></div>`
}

function loginView(){
document.getElementById("app").innerHTML=`<div class="auth"><div class="authbox"><div class="authbrand"><div class="mark">CC</div><div><b>CAPACITY CONNECT</b><small>Digital Capacity Building & Learning Management Portal</small></div></div><div class="row" style="justify-content:center"><span class="pill">SECURE DEMO</span><span class="pill blue">ROLE-BASED ACCESS</span></div><h1>Sign in</h1><p class="muted">Access your competency and learning workspace.</p><div class="field" style="margin-top:18px"><label>Email / Employee ID</label><input id="loginEmail" placeholder="employee@capacityconnect.local"></div><div class="field" style="margin-top:12px"><label>Password</label><div style="display:flex;gap:6px"><input id="loginPass" type="password" value="Demo@12345" style="flex:1"><button class="btn" onclick="let x=document.getElementById('loginPass');x.type=x.type==='password'?'text':'password'">Show</button></div></div><div class="between" style="margin:12px 0"><label><input type="checkbox" checked> Remember me</label><a href="#" onclick="toast('Password reset workflow opened');return false" style="font-size:12px">Forgot password?</a></div><button class="btn primary" style="width:100%;height:44px" onclick="demoLogin('Trainee')">Login</button><p class="muted" style="margin:15px 0 8px;font-size:11px">Quick demo access</p><div class="grid cards3 demo-grid"><button class="btn" onclick="demoLogin('Trainee')">Demo Trainee</button><button class="btn" onclick="demoLogin('Trainer')">Demo Trainer</button><button class="btn" onclick="demoLogin('Admin')">Demo Admin</button></div><button class="btn" style="width:100%;margin-top:12px" onclick="signup()">Create Account</button><p style="font-size:10px;color:var(--muted);margin-top:17px">Demo environment only. No real government credentials are processed.</p></div></div>`
}
function signup(){
state.signupStep=1;
openModal(`<div class="between"><div><h2>Create Account</h2><p class="muted">Registration requires administrative approval before activation.</p></div><span class="pill amber">PENDING APPROVAL</span></div><div class="stepper"><div class="active">1 · Account</div><div>2 · Professional</div><div>3 · Role</div><div>4 · Competency</div></div><div id="signupContent"></div>`);
signupStep();
}
function signupStep(){
const el=document.getElementById("signupContent");
if(state.signupStep===1)el.innerHTML=`<div class="formgrid"><div class="field"><label>Full Name</label><input id="sname"></div><div class="field"><label>Email</label><input type="email"></div><div class="field"><label>Mobile Number</label><input></div><div class="field"><label>Password</label><input type="password"></div><div class="field"><label>Confirm Password</label><input type="password"></div></div><div style="text-align:right;margin-top:16px"><button class="btn primary" onclick="state.signupStep=2;signupStep()">Next</button></div>`;
if(state.signupStep===2)el.innerHTML=`<div class="formgrid"><div class="field"><label>Organization</label><input value="IMD — DEMO"></div><div class="field"><label>Department</label><input></div><div class="field"><label>Designation</label><input></div><div class="field"><label>Location</label><input></div><div class="field"><label>Years of Experience</label><input type="number"></div><div class="field full"><label>Previous Training Information</label><textarea placeholder="Previous training programmes, subjects or relevant experience"></textarea></div></div><div class="between" style="margin-top:16px"><button class="btn" onclick="state.signupStep=1;signupStep()">Back</button><button class="btn primary" onclick="state.signupStep=3;signupStep()">Next</button></div>`;
if(state.signupStep===3)el.innerHTML=`<div class="formgrid"><div class="field"><label>Requested Role</label><select><option>Trainee</option><option>Trainer</option></select></div><div class="field"><label>Department</label><input placeholder="Forecasting / Training / Technical"></div><div class="field full"><div class="alert"><b>Admin accounts are not publicly selectable.</b><br>Administrator access is managed through organizational approval.</div></div></div><div class="between" style="margin-top:16px"><button class="btn" onclick="state.signupStep=2;signupStep()">Back</button><button class="btn primary" onclick="state.signupStep=4;signupStep()">Next</button></div>`;
if(state.signupStep===4)el.innerHTML=`<div class="formgrid"><div class="field full"><label>Initial Skills / Competencies</label><input placeholder="e.g. Forecast Analysis, Data Analysis, Python"></div><div class="field"><label>Qualifications</label><textarea placeholder="Degrees, certifications, professional qualifications"></textarea></div><div class="field"><label>Interests</label><textarea placeholder="Subjects and areas for development"></textarea></div><div class="field full"><label>Evidence</label><input type="file" multiple><small class="muted">Prototype: certificates and supporting documents can be attached for later verification.</small></div></div><div class="between" style="margin-top:16px"><button class="btn" onclick="state.signupStep=3;signupStep()">Back</button><button class="btn primary" onclick="closeModal();toast('Registration submitted — pending admin approval')">Submit Registration</button></div>`;
}

function dashboard(){
if(state.role==="Trainee")return page("Your Development Progress","Track competency growth, close skill gaps, and move from learning to verified capability.",`
<div class="development-hero">
  <div class="hero-copy">
    <span class="eyebrow">YOUR DEVELOPMENT JOURNEY</span>
    <h1>From competency assessment to verified capability.</h1>
    <p>CAPACITY CONNECT connects your profile, competency evidence, skill gaps, learning, trainer support and assessment in one continuous journey.</p>
  </div>
  <div class="readiness-card"><span>Overall readiness</span><strong>76%</strong><div class="progress"><i style="width:76%"></i></div><small>6 competencies verified · 1 priority gap</small></div>
</div>
<div class="journey-card section">
  <div class="between"><div><span class="eyebrow">DEVELOPMENT FLOW</span><h2>YOUR DEVELOPMENT JOURNEY</h2></div><button class="btn small" onclick="go('Competency Profile')">View competency profile</button></div>
  <div class="journey">
    <button class="journey-step done" onclick="go('My Profile')"><span>01</span><b>Profile</b><small>Complete</small></button>
    <div class="journey-line done"></div>
    <button class="journey-step done" onclick="go('Competency Assessment')"><span>02</span><b>Assessment</b><small>Completed</small></button>
    <div class="journey-line done"></div>
    <button class="journey-step current" onclick="go('Skill Gaps')"><span>03</span><b>Skill Gap</b><small>1 priority gap</small></button>
    <div class="journey-line"></div>
    <button class="journey-step" onclick="go('Recommended Learning')"><span>04</span><b>Learning</b><small>Recommended</small></button>
    <div class="journey-line"></div>
    <button class="journey-step" onclick="go('Trainer Matching')"><span>05</span><b>Trainer</b><small>94% match</small></button>
    <div class="journey-line"></div>
    <button class="journey-step" onclick="go('Assessments')"><span>06</span><b>Assessment</b><small>Next step</small></button>
    <div class="journey-line"></div>
    <button class="journey-step" onclick="go('Certificates')"><span>07</span><b>Certificate</b><small>Earn after completion</small></button>
  </div>
</div>
<div class="grid cards4 section">
  ${kpi("Competencies Verified","6","+1 this month","green")}
  ${kpi("Skill Gaps","1","Radar Analysis","amber")}
  ${kpi("Assessment Score","84%","+6% vs previous","teal")}
  ${kpi("Learning Progress","68%","+12% this month")}
</div>
<div class="competency-focus section">
  <div class="card competency-overview">
    <div class="between"><div><span class="eyebrow">COMPETENCY OVERVIEW</span><h2>Where you stand</h2></div><button class="btn small" onclick="go('Competency Profile')">View all</button></div>
    ${[["Technical Skills",72],["Communication",84],["Leadership",58],["Problem Solving",76]].map(x=>`<div class="skill-meter"><div class="between"><b>${x[0]}</b><b>${x[1]}%</b></div><div class="progress"><i style="width:${x[1]}%"></i></div></div>`).join("")}
  </div>
  <div class="card gap-focus">
    <span class="pill amber">PRIORITY SKILL GAP</span>
    <h2>Radar Analysis</h2>
    <p class="muted">Required: Advanced · Current: Beginner</p>
    <div class="gap-score"><strong>42%</strong><span>current level</span></div>
    <div class="progress"><i style="width:42%"></i></div>
    <p><b>58 percentage points</b> to close this competency gap.</p>
    <button class="btn primary" onclick="go('Recommended Learning')">View recommended learning</button>
  </div>
</div>
<div class="grid cards3 section">
  <div class="card"><span class="pill">VERIFIED TRAINER</span><h2>Dr. Ananya Sharma</h2><p class="muted">94% competency match · Radar Interpretation · Forecast Analysis</p><button class="btn primary" onclick="go('Trainer Matching')">View trainer match</button></div>
  <div class="card"><span class="pill blue">CONTINUE LEARNING</span><h2>Fundamentals of Weather Forecasting</h2><p class="muted">Next: Synoptic Analysis · Module 3</p><div class="progress"><i style="width:68%"></i></div><button class="btn primary small" style="margin-top:12px" onclick="go('My Learning')">Continue</button></div>
  <div class="card"><span class="pill blue">NEXT ASSESSMENT</span><h2>Atmospheric Observation Basics</h2><p class="muted">12 MCQs · Due 28 Sep 2026</p><button class="btn primary" onclick="go('Assessments')">Take assessment</button></div>
</div>`);
if(state.role==="Trainer")return page("Your Trainees & Competency Progress","Training delivery, competency-aligned support and trainee performance in one workspace.",`
<div class="development-hero compact">
  <div class="hero-copy"><span class="eyebrow">TRAINER WORKSPACE</span><h1>Support the right trainee at the right time.</h1><p>Prioritize competency gaps, monitor learner progress and connect expertise to development needs.</p></div>
  <div class="readiness-card"><span>Average performance</span><strong>81%</strong><div class="progress"><i style="width:81%"></i></div><small>42 assigned trainees · 14 assessments pending</small></div>
</div>
<div class="grid cards4 section">${kpi("Active Courses","8","+2 this quarter")}${kpi("Assigned Trainees","42","+6 this month")}${kpi("Pending Assessments","14","Requires review","amber")}${kpi("Average Performance","81%","+4%","green")}</div>
<div class="grid cards3 section"><div class="card"><span class="eyebrow">COMPETENCY DEMAND</span><h2>Where trainees need you</h2><div class="priority-list"><div><b>Radar Analysis</b><span>6 trainees</span></div><div><b>Forecast Analysis</b><span>11 trainees</span></div><div><b>Climate Data</b><span>8 trainees</span></div></div><button class="btn primary" style="margin-top:15px" onclick="go('Assigned Trainees')">Review assigned trainees</button></div><div class="card"><h2>Performance Overview</h2><div class="chart">${[52,65,76,61,84,72].map((v,i)=>`<div class="bar"><i style="height:${v}%"></i><span>W${i+1}</span></div>`).join("")}</div></div><div class="card"><h2>Quick Actions</h2><button class="btn primary" onclick="go('Create Course')">Create course</button><button class="btn" style="margin-left:6px" onclick="go('Questionnaires')">Create questionnaire</button><button class="btn teal" style="margin-top:9px" onclick="go('Trainer Library')">Upload resource</button></div></div>`);
return page("Training Ecosystem Overview","Organization-wide visibility into users, learning activity, competency development and participation.",`
<div class="development-hero compact">
  <div class="hero-copy"><span class="eyebrow">ADMIN WORKSPACE</span><h1>Monitor the training ecosystem.</h1><p>Track participation, competency development, courses and actions that keep the learning programme moving.</p></div>
  <div class="readiness-card"><span>Course completion</span><strong>76%</strong><div class="progress"><i style="width:76%"></i></div><small>4,782 total enrollments · 2,936 certificates</small></div>
</div>
<div class="grid cards4 section">${kpi("Total Users","1,248","+8.4%")}${kpi("Active Trainees","1,086","+5.2%","teal")}${kpi("Trainers","162","+3.1%","green")}${kpi("Active Courses","48","+6","amber")}</div>
<div class="grid cards3 section"><div class="card"><span class="eyebrow">LEARNING ACTIVITY</span><h2>Monthly participation</h2><div class="chart">${[42,58,50,71,64,82,90].map((v,i)=>`<div class="bar"><i style="height:${v}%"></i><span>${["Apr","May","Jun","Jul","Aug","Sep","Oct"][i]}</span></div>`).join("")}</div></div><div class="card"><span class="eyebrow">COMPETENCY</span><h2>Priority gaps</h2><div class="stat-emphasis">184</div><p class="muted">Competency gaps across monitored roles</p><button class="btn primary" onclick="go('Competency Mapping')">Review competency map</button></div><div class="card"><span class="eyebrow">ACTION QUEUE</span><h2>What needs attention</h2><p>12 accounts awaiting approval</p><p>6 courses submitted for review</p><p>38 certificates issued this week</p><p>214 assessments completed</p><button class="btn primary" onclick="go('User Approval')">Open approvals</button></div></div>`);
}
function profile(){
if(state.role==="Trainee")return page("My Profile","Structured professional profile used as an input to competency mapping.",`<div class="card"><div class="between"><div><h2 style="margin:0">Arjun Mehta</h2><p class="muted">Trainee · Weather Forecaster · DEMO</p></div><span class="pill">Profile 92% complete</span></div><hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><div class="formgrid"><div><b>Personal Information</b><p>Email: arjun.mehta@demo.example<br>Mobile: +91 98765 43210<br>Location: New Delhi</p></div><div><b>Professional Information</b><p>Organization: IMD — DEMO<br>Department: Forecasting<br>Designation: Weather Forecaster<br>Experience: 4 years</p></div><div><b>Qualifications</b><p>B.Sc. Atmospheric Science · National Institute — DEMO · 2022</p></div><div><b>Previous Training</b><p>Weather Observation · Synoptic Analysis · Climate Data Fundamentals</p></div><div class="full"><b>Skills</b><p>${["Forecast Analysis","Python","Weather Forecasting","GIS","Data Analysis"].map(x=>`<span class="tag">${x}</span>`).join(" ")}</p></div><div class="full"><b>Interests</b><p><span class="tag">Radar Meteorology</span> <span class="tag">Satellite Products</span> <span class="tag">Climate Data</span></p></div><div class="full"><b>Certificates & Evidence</b><p>Weather Observation Fundamentals · <span class="pill">Verified</span> &nbsp; Data Analysis Essentials · <span class="pill">Verified</span></p></div></div><div style="margin-top:18px"><button class="btn primary" onclick="editTraineeProfile()">Edit Profile</button><button class="btn" style="margin-left:6px" onclick="go('Competency Assessment')">Complete Competency Assessment</button></div></div>`);
return page("Trainer Profile","Expertise, credentials and training experience used for trainer matching.",`<div class="card"><div class="between"><div><h2 style="margin:0">Dr. Ananya Sharma</h2><p class="muted">Senior Meteorological Trainer · IMD — DEMO</p></div><span class="pill">Verified Trainer</span></div><div class="formgrid" style="margin-top:20px"><div><b>Qualifications</b><p>M.Sc. Meteorology · DEMO · 2014<br>Ph.D. Atmospheric Sciences · DEMO · 2018</p></div><div><b>Training Experience</b><p>11 years · Training & Capacity Building</p></div><div class="full"><b>Expertise & Skills</b><p>${["Forecast Analysis","Synoptic Meteorology","Radar Interpretation","Climate Data","Python"].map(x=>`<span class="tag">${x}</span>`).join(" ")}</p></div><div class="full"><b>Credentials</b><p>Advanced Forecasting Certification · Trainer Development Programme <span class="pill">Credentials Verified</span></p></div></div><button class="btn primary" style="margin-top:15px" onclick="toast('Trainer profile edit mode enabled')">Edit Profile</button></div>`);
}
function editTraineeProfile(){openModal(`<h2>Edit Professional Profile</h2><div class="formgrid"><div class="field"><label>Designation</label><input value="Weather Forecaster"></div><div class="field"><label>Department</label><input value="Forecasting"></div><div class="field"><label>Qualifications</label><textarea>B.Sc. Atmospheric Science</textarea></div><div class="field"><label>Interests</label><textarea>Radar Meteorology, Satellite Products, Climate Data</textarea></div><div class="field full"><label>Skills</label><input value="Forecast Analysis, Python, Weather Forecasting, GIS, Data Analysis"></div><div class="field full"><label>Previous Training</label><textarea>Weather Observation; Synoptic Analysis; Climate Data Fundamentals</textarea></div></div><button class="btn primary" style="margin-top:15px" onclick="closeModal();state.profileSaved=true;persist();notify("Professional profile updated","Trainee");toast("Profile updated successfully")">Save Profile</button>`)}
function competencyAssessment(){
return page("Competency Assessment & Evidence","Self-assessment, previous training and supporting evidence feed the competency engine.",`<div class="card section"><div class="between"><div><h2>Competency Self-Assessment</h2><p class="muted">Rate your current proficiency honestly. These values are inputs, not final verified competency levels.</p></div><span class="pill blue">INPUT TO ENGINE</span></div>${competencies.map((c,i)=>`<div style="margin:15px 0"><div class="between"><b>${c[0]}</b><select style="width:180px;padding:7px;border:1px solid var(--line);border-radius:6px"><option>${c[1]}</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></div><div class="progress" style="margin-top:7px"><i style="width:${c[3]}%"></i></div></div>`).join("")}<button class="btn primary" onclick="toast('Self-assessment saved for competency engine processing')">Save Self-Assessment</button></div><div class="grid cards2 section"><div class="card"><h2>Previous Training Records</h2><div class="field"><label>Training / Course</label><input value="Weather Observation Fundamentals"></div><div class="field" style="margin-top:10px"><label>Completion Date</label><input value="18 Aug 2026"></div><button class="btn small" style="margin-top:10px" onclick="toast('Training record added')">Add Training Record</button></div><div class="card"><h2>Evidence & Certificates</h2><p class="muted">Upload evidence supporting qualifications, skills and previous training.</p><input type="file" multiple><div style="margin-top:12px"><span class="tag">Weather Observation Certificate.pdf</span><span class="pill">Verified</span></div><div style="margin-top:9px"><span class="tag">Data Analysis Certificate.pdf</span><span class="pill">Verified</span></div><button class="btn primary" style="margin-top:13px" onclick="state.verifiedEvidence=true;state.evidenceStatus="Pending Verification";persist();notify("Evidence submitted and is pending admin verification","Admin");toast("Evidence submitted for verification")">Submit Evidence</button></div></div><div class="card section"><h2>Verification Status</h2><div class="tablewrap"><table><thead><tr><th>Evidence</th><th>Type</th><th>Status</th><th>Reviewed By</th></tr></thead><tbody><tr><td>Weather Observation Fundamentals</td><td>Certificate</td><td><span class="pill">Verified</span></td><td>Admin — DEMO</td></tr><tr><td>Data Analysis Essentials</td><td>Certificate</td><td><span class="pill">Verified</span></td><td>Admin — DEMO</td></tr><tr><td>Radar Analysis Experience</td><td>Self-declared</td><td><span class="pill amber">Needs Review</span></td><td>Pending</td></tr></tbody></table></div></div>`)
}
function competencyProfile(){
return page("Competency Profile","Verified competencies compared with the requirements associated with the trainee's role.",`<div class="grid cards3"><div class="card"><h2>Role Requirement</h2><h3>Weather Forecaster</h3><p class="muted">Required competencies are maintained through the competency framework.</p><span class="tag">Forecast Analysis</span><span class="tag">Radar Analysis</span><span class="tag">Observation</span><span class="tag">Weather Data Interpretation</span></div><div class="card"><h2>Verified Readiness</h2><div class="row"><div class="ring"><b>76%</b></div><div><b>6 verified</b><p class="muted">1 gap · 1 needs review</p></div></div></div><div class="card"><h2>Engine Output</h2><p><b>Skill Gap:</b> Radar Analysis</p><p><b>Recommended:</b> Radar Interpretation Fundamentals</p><p><b>Trainer:</b> Dr. Ananya Sharma</p><span class="pill">Verified Match</span></div></div><div class="card section"><div class="between"><h2>Competency Matrix</h2><button class="btn small" onclick="go('Skill Gaps')">View Skill Gaps</button></div><div class="tablewrap"><table><thead><tr><th>Competency</th><th>Current</th><th>Required</th><th>Evidence</th><th>Status</th><th>Score</th></tr></thead><tbody>${competencies.map(c=>`<tr><td><b>${c[0]}</b></td><td>${c[1]}</td><td>${c[0]==="Radar Analysis"?"Advanced":c[1]}</td><td>${c[2]==="Verified"?"Certificate / Record":"Self-assessment"}</td><td><span class="pill ${c[2]==="Gap"?"amber":""}">${c[2]}</span></td><td>${c[3]}%</td></tr>`).join("")}</tbody></table></div></div><div class="card section"><h2>Continuous Competency Development</h2><div class="workflow">${["Current Profile","Re-evaluate Gap","Learning","Assessment","Updated Profile","Continuous Development"].map((x,i)=>`<div class="flow">${i+1}. ${x}</div>`).join("")}</div></div>`)
}
function skillGaps(){return page("Skill Gaps","Competency Engine output: missing or weak competencies linked to learning and trainer matching.",`<div class="grid cards3"><div class="card"><span class="pill amber">PRIORITY GAP</span><h2 style="margin-top:10px">Radar Analysis</h2><p class="muted">Required: Advanced · Current: Beginner</p><div class="progress"><i style="width:42%"></i></div><p><b>Gap:</b> 58 percentage points</p><button class="btn primary" onclick="go('Recommended Learning')">Find Learning</button></div><div class="card"><span class="pill gray">NEEDS REVIEW</span><h2 style="margin-top:10px">GIS</h2><p class="muted">Evidence requires review before competency is verified.</p><button class="btn" onclick="go('Competency Assessment')">Review Evidence</button></div><div class="card"><span class="pill">MATCHED</span><h2 style="margin-top:10px">Forecast Analysis</h2><p class="muted">Current: Advanced · Required: Advanced</p><div class="progress"><i style="width:90%"></i></div></div></div><div class="card section"><h2>How the Gap Was Identified</h2><div class="arch"><div class="arch-col"><div class="arch-head">USER INPUTS</div><div class="arch-item">Employee Profile</div><div class="arch-item">Skills & Qualifications</div><div class="arch-item">Previous Training</div><div class="arch-item">Verified Evidence</div></div><div class="arch-col"><div class="arch-head">COMPETENCY ENGINE</div><div class="arch-item">Credential Validation</div><div class="arch-item">Competency Mapping</div><div class="arch-item">Skill-Gap Analysis</div></div><div class="arch-col"><div class="arch-head">OUTPUTS</div><div class="arch-item">Skill Gap Insights</div><div class="arch-item">Recommended Courses</div><div class="arch-item">Verified Trainer Match</div></div></div></div>`)
}
function recommended(){return page("Recommended Learning","Courses and learning resources matched to identified competency gaps.",`<div class="notice"><b>Recommendation logic:</b> Skill gap → Course Matching → Trainer Matching → Recommended Learning Path.</div><div class="grid cards3 section">${courses.map((c,i)=>`<div class="card"><div class="between"><span class="pill ${i===1?"":"blue"}">${i===1?"RECOMMENDED":"AVAILABLE"}</span><span class="muted">${c.level}</span></div><h3 style="margin-top:10px">${c.title}</h3><p class="muted">${c.desc}</p><div>${c.skills.map(s=>`<span class="tag">${s}</span>`).join("")}</div><p style="font-size:11px"><b>Addresses:</b> ${i===0?"Forecast Analysis":i===1?"Data Analysis":i===3?"Radar / Satellite interpretation":"Observation / preparedness"}</p><button class="btn ${i===1?"primary":"small"}" onclick="openCourse(${c.id})">${i===1?"Enroll in Recommended Course":"View Course"}</button></div>`).join("")}</div><div class="card section"><h2>Recommended Learning Path</h2><div class="workflow">${["Radar Gap","Radar Interpretation","Dr. Ananya Sharma","MCQ Assessment","Competency Update"].map((x,i)=>`<div class="flow">${i+1}. ${x}</div>`).join("")}</div></div>`)
}
function trainerMatching(){return page("Trainer Matching","Verified trainer expertise matched to the subject and competency requirement.",`<div class="card"><div class="between"><div><h2>Requirement: Radar Analysis</h2><p class="muted">Required level: Advanced · Trainee gap: Beginner</p></div><span class="pill">VERIFIED MATCHING</span></div></div><div class="grid cards3 section">${trainerMatches.map(t=>`<div class="card"><div class="between"><div class="badge-icon">TR</div><span class="pill">${t.match}% match</span></div><h3 style="margin-top:12px">${t.name}</h3><p class="muted">${t.expertise}</p><p><span class="pill">Verified Credentials</span></p><p class="muted" style="font-size:11px">Recommended course: ${t.course}</p><button class="btn primary" onclick="toast('Trainer selected for demonstration learning path')">Select Trainer</button></div>`).join("")}</div><div class="card section"><h2>Matching Logic</h2><div class="arch"><div class="arch-col"><div class="arch-head">SUBJECT REQUIREMENT</div><div class="arch-item">Radar Analysis</div><div class="arch-item">Advanced Level</div></div><div class="arch-col"><div class="arch-head">TRAINER MATCHING</div><div class="arch-item">Expertise Match</div><div class="arch-item">Credential Validation</div><div class="arch-item">Trainer Verification</div></div><div class="arch-col"><div class="arch-head">OUTCOME</div><div class="arch-item">Verified Trainer Match</div><div class="arch-item">Targeted Learning</div></div></div></div>`)
}
function catalogue(){return page("Course Catalogue","Browse organizational learning programmes.",`<div class="card"><div class="formgrid"><div class="field"><label>Search courses</label><input placeholder="Search by course, subject or skill" oninput="filterCourses(this.value)"></div><div class="field"><label>Level</label><select onchange="filterCourses(document.querySelector('.field input').value,this.value)"><option>All levels</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></div></div></div><div id="courseGrid" class="grid cards3 section">${courseCards(courses)}</div>`)}
function courseCards(list){return list.map(c=>`<div class="card"><div class="between"><span class="pill blue">${c.level}</span><span class="muted">${c.duration}</span></div><h3 style="margin-top:10px">${c.title}</h3><p class="muted">${c.desc}</p><p><b>Trainer:</b> ${c.trainer}</p><div>${c.skills.map(s=>`<span class="tag">${s}</span>`).join("")}</div><div class="between" style="margin-top:13px"><small>${c.learners} learners · DEMO</small><button class="btn primary small" onclick="openCourse(${c.id})">View Course</button></div></div>`).join("")}
function filterCourses(q="",level="All levels"){const l=level||"All levels";const a=courses.filter(c=>(c.title+c.desc+c.skills.join(" ")).toLowerCase().includes((q||"").toLowerCase())&&(l==="All levels"||c.level===l));const g=document.getElementById("courseGrid");if(g)g.innerHTML=courseCards(a)}
function openCourse(id){const c=courses.find(x=>x.id===id);openModal(`<div class="between"><div><h2>${c.title}</h2><p class="muted">${c.desc}</p></div><span class="pill blue">${c.level}</span></div><div class="formgrid"><div><b>Learning Objectives</b><p>Apply subject knowledge, interpret operational information and develop role-aligned competency.</p></div><div><b>Competencies</b><p>${c.skills.join(" · ")}</p></div><div><b>Learning Resources</b><p>Recorded lecture · Presentation · Study material · Reference document</p></div><div><b>Assessment</b><p>Subject-wise MCQ assessment after learning.</p></div></div><div class="between" style="margin-top:15px"><span class="pill">DEMO COURSE</span><button class="btn primary" onclick="closeModal();go('My Learning');toast('Course enrolled successfully')">Enroll Now</button></div>`)}
function learning(){return page("My Learning","Enrolled programmes and learning progress.",`<div class="card"><div class="between"><div><h2>Fundamentals of Weather Forecasting</h2><p class="muted">Trainer: Dr. Ananya Sharma · Module 3 of 4</p></div><span class="pill">68% COMPLETE</span></div><div class="progress" style="margin:14px 0"><i style="width:68%"></i></div><div class="between"><span>68% complete</span><button class="btn primary" onclick="go('Learning Resources')">Continue Learning</button></div></div><div class="grid cards3 section">${courses.slice(1).map(c=>`<div class="card"><h3>${c.title}</h3><p class="muted">${c.progress?c.progress+"% complete":"Not started"}</p><div class="progress"><i style="width:${c.progress}%"></i></div><button class="btn small" style="margin-top:12px" onclick="openCourse(${c.id})">View Course</button></div>`).join("")}</div>`)}
function resources(){return page("Learning Resources","Recorded lectures, presentations, study materials and reference content.",`<div class="card"><div class="formgrid"><div class="field"><label>Search resources</label><input placeholder="Search by title or subject"></div><div class="field"><label>Type</label><select><option>All resources</option><option>Recorded Lecture</option><option>Presentation</option><option>Study Material</option><option>Reference Document</option></select></div></div></div><div class="tablewrap section"><table><thead><tr><th>Resource</th><th>Subject</th><th>Type</th><th>Trainer</th><th>Availability</th><th>Action</th></tr></thead><tbody><tr><td>Radar Interpretation Guide</td><td>Weather Forecasting</td><td>PDF</td><td>Dr. Ananya Sharma</td><td><span class="pill">Published</span></td><td><button class="btn small" onclick="toast('Resource opened')">View</button></td></tr><tr><td>Synoptic Analysis Lecture</td><td>Forecasting</td><td>Video</td><td>Dr. Ananya Sharma</td><td><span class="pill">Published</span></td><td><button class="btn small" onclick="toast('Recorded lecture opened')">Play</button></td></tr><tr><td>Climate Data Workbook</td><td>Climate Data</td><td>PDF</td><td>Dr. R. Menon</td><td><span class="pill">Published</span></td><td><button class="btn small" onclick="toast('Study material opened')">View</button></td></tr></tbody></table></div>`)}
function assessments(){return page("Assessments","Subject-wise MCQs, deadlines and assessment results.",`<div class="card"><div class="between"><div><span class="pill">READY</span><h2 style="margin-top:9px">Atmospheric Observation Basics</h2><p class="muted">12 questions · 20 minutes · Subject: Meteorological Observation · Deadline: 28 Sep 2026</p></div><button class="btn primary" onclick="startAssessment()">Take Assessment</button></div></div>${state.assessmentDone?`<div class="card section"><h2>Latest Assessment Result</h2><div class="grid cards4">${kpi("Score","3/4","Completed","green")}${kpi("Percentage","75%","Recorded","teal")}${kpi("Correct","3","Subject MCQ","green")}${kpi("Competency Update","+8","Contribution","purple")}</div></div>`:""}<div class="card section"><h2>Assessment Record</h2><div class="tablewrap"><table><thead><tr><th>Assessment</th><th>Subject</th><th>Deadline</th><th>Status</th><th>Result</th></tr></thead><tbody><tr><td>Atmospheric Observation Basics</td><td>Meteorological Observation</td><td>28 Sep 2026</td><td><span class="pill">Ready</span></td><td>—</td></tr><tr><td>Synoptic Analysis Check</td><td>Weather Forecasting</td><td>Completed</td><td><span class="pill">Completed</span></td><td>83%</td></tr></tbody></table></div></div>`)}
function startAssessment(){state.assessment=0;state.answers={};openModal(`<div id="assessmentBox"></div>`);renderAssessment()}
function renderAssessment(){const q=qs[state.assessment];document.getElementById("assessmentBox").innerHTML=`<div class="between"><span class="pill blue">QUESTION ${state.assessment+1} OF ${qs.length}</span><b>20:00</b></div><h2 style="margin-top:18px">${q[0]}</h2>${q[1].map((o,i)=>`<label style="display:block;padding:12px;border:1px solid var(--line);border-radius:7px;margin:8px 0"><input type="radio" name="q" value="${i}" ${state.answers[state.assessment]===i?"checked":""}> ${String.fromCharCode(65+i)}. ${o}</label>`).join("")}<div class="between" style="margin-top:18px"><button class="btn" onclick="if(state.assessment>0){state.answers[state.assessment]=+document.querySelector('input[name=q]:checked')?.value;state.assessment--;renderAssessment()}">Previous</button><button class="btn primary" onclick="state.answers[state.assessment]=+document.querySelector('input[name=q]:checked')?.value;if(state.assessment<qs.length-1){state.assessment++;renderAssessment()}else{state.assessmentDone=true;state.assessmentScore=qs.reduce((n,q,i)=>n+(state.answers[i]===q[2]?1:0),0);persist();notify("Assessment completed; competency progress updated","Trainee");closeModal();go('Assessments');toast("Assessment submitted and result calculated")}">${state.assessment===qs.length-1?"Submit Assessment":"Next"}</button></div>`}
function certificates(){return page("Certificates","Completed learning credentials and certification records.",`<div class="tablewrap"><table><thead><tr><th>Certificate</th><th>Course</th><th>Issue Date</th><th>ID</th><th>Status</th><th></th></tr></thead><tbody><tr><td>Weather Observation Fundamentals</td><td>Meteorological Observation</td><td>18 Aug 2026</td><td>CC-DEMO-1024</td><td><span class="pill">Issued</span></td><td><button class="btn small" onclick="certificate()">View</button></td></tr><tr><td>Data Analysis Essentials</td><td>Climate Data Analysis</td><td>03 Jul 2026</td><td>CC-DEMO-0987</td><td><span class="pill">Issued</span></td><td><button class="btn small" onclick="certificate()">View</button></td></tr></tbody></table></div>`)}
function certificate(){openModal(`<div style="border:7px double var(--navy);padding:30px;text-align:center"><div class="muted">CAPACITY CONNECT · DEMONSTRATION CERTIFICATE</div><h1 style="color:var(--navy)">Certificate of Completion</h1><p>This certifies that</p><h2>Arjun Mehta</h2><p>has successfully completed</p><h2>Weather Observation Fundamentals</h2><p>Certificate ID: CC-DEMO-1024 · Issue Date: 18 Aug 2026</p><span class="pill">DEMO / NOT AN OFFICIAL CREDENTIAL</span></div>`)}
function feedback(){return page("Feedback","Share your learning experience and training-content feedback.",`<div class="card"><div class="formgrid"><div class="field"><label>Course</label><select><option>Fundamentals of Weather Forecasting</option><option>Climate Data Analysis</option></select></div><div class="field"><label>Content Quality</label><select><option>5 — Excellent</option><option>4 — Good</option><option>3 — Average</option></select></div><div class="field"><label>Trainer Effectiveness</label><select><option>5 — Excellent</option><option>4 — Good</option></select></div><div class="field"><label>Learning Experience</label><select><option>5 — Excellent</option><option>4 — Good</option></select></div><div class="field full"><label>Comments</label><textarea placeholder="Share feedback about the course or learning content"></textarea></div></div><button class="btn primary" style="margin-top:15px" onclick="toast('Feedback submitted successfully')">Submit Feedback</button></div>`)}
function notifications(){return page("Notifications","Training, competency, assessment and administrative updates.",`<div class="grid cards3"><div class="card"><span class="pill">NEW</span><h3 style="margin-top:9px">Competency review completed</h3><p class="muted">Your Weather Observation evidence has been verified.</p><small>Today · 10:24 AM</small></div><div class="card"><span class="pill blue">LEARNING</span><h3 style="margin-top:9px">New learning content</h3><p class="muted">Radar Interpretation Guide has been published.</p><small>Yesterday · 4:10 PM</small></div><div class="card"><span class="pill amber">ACTION</span><h3 style="margin-top:9px">Assessment due</h3><p class="muted">Atmospheric Observation Basics is due 28 Sep 2026.</p><button class="btn small" onclick="go('Assessments')">Open Assessment</button></div></div>`)}
function settings(){return page("Settings","Manage account, notification and accessibility preferences.",`<div class="card"><div class="formgrid"><div class="field"><label>Email notifications</label><select><option>Enabled</option><option>Disabled</option></select></div><div class="field"><label>Assessment alerts</label><select><option>Immediate</option><option>Daily summary</option></select></div><div class="field"><label>Dashboard view</label><select><option>Competency overview</option><option>Learning overview</option></select></div><div class="field"><label>Language</label><select><option>English</option></select></div><div class="field"><label>Accessibility</label><select><option>Standard contrast</option><option>High contrast</option></select></div><div class="field"><label>Session security</label><select><option>Remember device</option><option>Ask every time</option></select></div></div><button class="btn primary" style="margin-top:18px" onclick="toast('Settings saved successfully')">Save Settings</button></div>`)}
function trainerPage(){
if(state.page==="My Courses")return page("My Courses","Manage published and draft training programmes.",`<div class="grid cards3">${courses.slice(0,3).map((c,i)=>`<div class="card"><div class="between"><span class="pill ${i===2?"amber":""}">${i===2?"DRAFT":"PUBLISHED"}</span><span>${c.learners} learners</span></div><h3 style="margin-top:10px">${c.title}</h3><p class="muted">${c.desc}</p><div class="progress"><i style="width:${82-i*18}%"></i></div><div class="between" style="margin-top:10px"><span>${82-i*18}% completion</span><button class="btn small" onclick="toast('Course management opened')">Manage</button></div></div>`).join("")}</div>`);
if(state.page==="Create Course")return page("Create Course","Create a learning programme linked to competencies and assessments.",`<div class="card"><div class="formgrid"><div class="field"><label>Course Title</label><input value="Radar Interpretation Fundamentals"></div><div class="field"><label>Level</label><select><option>Advanced</option><option>Intermediate</option></select></div><div class="field full"><label>Description</label><textarea>Training covering radar products, interpretation and operational application.</textarea></div><div class="field"><label>Target Competencies</label><input value="Radar Analysis, Forecast Analysis"></div><div class="field"><label>Duration</label><input value="4 weeks"></div><div class="field"><label>Assessment</label><select><option>Subject-wise MCQ</option><option>Questionnaire</option></select></div><div class="field"><label>Visibility</label><select><option>Submit for admin review</option><option>Draft</option></select></div></div><button class="btn primary" style="margin-top:17px" onclick="toast('Course submitted for administrative review')">Save & Submit</button></div>`);
if(state.page==="Questionnaires")return page("Questionnaires","Create subject-wise questionnaires with deadlines.",`<div class="card"><div class="formgrid"><div class="field"><label>Questionnaire Title</label><input value="Radar Analysis Readiness Check"></div><div class="field"><label>Subject</label><input value="Radar Analysis"></div><div class="field"><label>Deadline</label><input value="05 Oct 2026"></div><div class="field"><label>Questions</label><input value="15"></div><div class="field full"><label>Instructions</label><textarea>Complete the questionnaire before the deadline. Results contribute to performance monitoring.</textarea></div></div><button class="btn primary" style="margin-top:15px" onclick="toast('Questionnaire published with deadline')">Publish Questionnaire</button></div>`);
if(state.page==="Assessments")return page("Assessments","Create, publish and monitor subject-wise assessments.",`<div class="tablewrap"><table><thead><tr><th>Assessment</th><th>Course</th><th>Questions</th><th>Submissions</th><th>Deadline</th><th>Status</th></tr></thead><tbody><tr><td>Atmospheric Observation Basics</td><td>Meteorological Observation</td><td>12</td><td>86</td><td>28 Sep 2026</td><td><span class="pill">Published</span></td></tr><tr><td>Synoptic Analysis Check</td><td>Weather Forecasting</td><td>15</td><td>64</td><td>30 Sep 2026</td><td><span class="pill">Published</span></td></tr></tbody></table></div>`);
if(state.page==="Assigned Trainees")return page("Assigned Trainees","Trainees connected to your expertise through competency-based matching.",`<div class="tablewrap"><table><thead><tr><th>Trainee</th><th>Role</th><th>Competency Gap</th><th>Match</th><th>Evidence</th><th>Action</th></tr></thead><tbody><tr><td>Arjun Mehta</td><td>Weather Forecaster</td><td>Radar Analysis</td><td>94%</td><td><span class="pill">Verified</span></td><td><button class="btn small" onclick="go('Trainee Performance')">Review</button></td></tr><tr><td>Neha Das</td><td>Forecast Analyst</td><td>Synoptic Analysis</td><td>91%</td><td><span class="pill">Verified</span></td><td><button class="btn small" onclick="go('Trainee Performance')">Review</button></td></tr></tbody></table></div>`);
if(state.page==="Trainee Performance")return page("Trainee Performance","Monitor participation, questionnaire results and competency progress.",`<div class="tablewrap"><table><thead><tr><th>Trainee</th><th>Participation</th><th>Assessment</th><th>Competency</th><th>Evidence</th><th>Action</th></tr></thead><tbody><tr><td>Arjun Mehta</td><td>92%</td><td>83%</td><td>Radar Analysis · Beginner</td><td><span class="pill">2 Verified</span></td><td><button class="btn small" onclick="openPerformance()">Review & Verify</button></td></tr><tr><td>Neha Das</td><td>88%</td><td>91%</td><td>Synoptic Analysis · Intermediate</td><td><span class="pill">Verified</span></td><td><button class="btn small" onclick="openPerformance()">Review</button></td></tr></tbody></table></div>`);
if(state.page==="Trainer Library")return page("Trainer Library","Publish recorded lectures, presentations and study materials for trainees.",`<div class="card"><div class="between"><div><h2>Learning Resources</h2><p class="muted">Centralized trainer-managed knowledge sharing.</p></div><button class="btn primary" onclick="uploadResource()">Upload Resource</button></div><div class="tablewrap section"><table><thead><tr><th>Resource</th><th>Subject</th><th>Type</th><th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody><tr><td>Radar Interpretation Guide</td><td>Radar Analysis</td><td>PDF</td><td>22 Sep 2026</td><td><span class="pill">Published</span></td><td><button class="btn small" onclick="toast('Resource preview opened')">View</button></td></tr><tr><td>Synoptic Analysis Lecture</td><td>Forecasting</td><td>Video</td><td>18 Sep 2026</td><td><span class="pill">Published</span></td><td><button class="btn small" onclick="toast('Lecture opened')">View</button></td></tr><tr><td>Climate Data Workbook</td><td>Climate Data</td><td>PDF</td><td>12 Sep 2026</td><td><span class="pill amber">Draft</span></td><td><button class="btn small" onclick="toast('Resource editor opened')">Edit</button></td></tr></tbody></table></div></div>`);
if(state.page==="Competency Mapping")return page("Competency Mapping","Connect subject requirements with trainer expertise and verified credentials.",`<div class="card"><div class="between"><div><h2>Trainer Competency Match</h2><p class="muted">Example mapping for Weather Forecasting.</p></div><span class="pill">92% MATCH</span></div><div class="workflow">${["Subject Requirement","Required Competencies","Trainer Skills","Credential Validation","Suitable Trainer"].map((x,i)=>`<div class="flow">${i+1}. ${x}</div>`).join("")}</div></div><div class="grid cards3 section">${trainerMatches.map(t=>`<div class="card"><h3>${t.name}</h3><p class="muted">${t.expertise}</p><div class="progress"><i style="width:${t.match}%"></i></div><div class="between" style="margin-top:8px"><span>${t.match}% match</span><span class="pill">Verified</span></div><button class="btn teal" style="margin-top:12px" onclick="toast('Trainer assignment saved in demo state')">Assign Trainer</button></div>`).join("")}</div>`);
if(state.page==="Notifications")return notifications();
if(state.page==="Settings")return settings();
return page(state.page,"Trainer workspace.",`<div class="card"><h2>${state.page}</h2><p class="muted">Use the trainer navigation to manage professional profile, courses, questionnaires, assessments, assigned trainees, performance, resources and competency mapping.</p></div>`);
}
function openPerformance(){openModal(`<h2>Trainee Competency Review</h2><p class="muted">Arjun Mehta · Weather Forecaster</p><div class="tablewrap"><table><thead><tr><th>Competency</th><th>Claimed</th><th>Evidence</th><th>Trainer Review</th></tr></thead><tbody><tr><td>Radar Analysis</td><td>Beginner</td><td>Experience record</td><td><select><option>Needs development</option><option>Intermediate</option><option>Advanced</option></select></td></tr><tr><td>Forecast Analysis</td><td>Advanced</td><td>Certificate + record</td><td><select><option>Verified</option><option>Review</option></select></td></tr></tbody></table></div><textarea style="width:100%;margin-top:12px;border:1px solid var(--line);padding:10px;border-radius:7px" placeholder="Trainer remarks"></textarea><button class="btn primary" style="margin-top:12px" onclick="closeModal();toast('Trainer review saved')">Save Review</button>`)}
function uploadResource(){openModal(`<h2>Upload Learning Resource</h2><div class="formgrid"><div class="field"><label>Title</label><input value="Radar Interpretation Guide"></div><div class="field"><label>Type</label><select><option>Recorded Lecture</option><option>Presentation</option><option>Study Material</option><option>Reference Document</option></select></div><div class="field"><label>Subject</label><input value="Radar Analysis"></div><div class="field"><label>Target Competency</label><input value="Radar Analysis"></div><div class="field full"><label>File</label><input type="file"></div></div><button class="btn primary" style="margin-top:15px" onclick="closeModal();toast('Resource uploaded to Trainer Library demo')">Upload</button>`)}
function adminPage(){
if(state.page==="User Approval")return page("User Approval","Approve new accounts before role-based access is activated.",`<div class="alert"><b>Administrative approval is required</b> before a new account becomes active.</div><div class="tablewrap section"><table><thead><tr><th>Name</th><th>Organization</th><th>Requested Role</th><th>Evidence</th><th>Submitted</th><th>Action</th></tr></thead><tbody><tr><td>Rahul Singh</td><td>IMD — DEMO</td><td>Trainee</td><td><span class="pill">2 documents</span></td><td>25 Sep 2026</td><td><button class="btn small primary" onclick="approveUser('Rahul Singh')">Approve</button> <button class="btn small danger" onclick="toast('User marked for review')">Review</button></td></tr><tr><td>Meera Joseph</td><td>IMD — DEMO</td><td>Trainer</td><td><span class="pill amber">1 document</span></td><td>24 Sep 2026</td><td><button class="btn small primary" onclick="approveUser('Meera Joseph')">Approve</button></td></tr></tbody></table></div>`);
if(state.page==="User Management")return page("User Management","Manage users, approval status and organizational access.",`<div class="tablewrap"><table><thead><tr><th>User</th><th>Role</th><th>Department</th><th>Status</th><th>Last Activity</th><th>Action</th></tr></thead><tbody><tr><td>Arjun Mehta</td><td>Trainee</td><td>Forecasting</td><td><span class="pill">Active</span></td><td>Today</td><td><button class="btn small" onclick="toast('User record opened')">View</button></td></tr><tr><td>Dr. Ananya Sharma</td><td>Trainer</td><td>Training</td><td><span class="pill">Active</span></td><td>Today</td><td><button class="btn small" onclick="toast('User record opened')">View</button></td></tr><tr><td>Rahul Singh</td><td>Trainee</td><td>Forecasting</td><td><span class="pill amber">Pending</span></td><td>—</td><td><button class="btn small primary" onclick="approveUser('Rahul Singh')">Approve</button></td></tr></tbody></table></div>`);
if(state.page==="Role Management")return page("Role Management","Manage role assignments and role-based access control.",`<div class="grid cards3"><div class="card"><span class="pill blue">TRAINEE</span><h3 style="margin-top:10px">Learning & Development</h3><p class="muted">Profile · Competency · Learning · Assessments · Feedback · Certificates</p></div><div class="card"><span class="pill blue">TRAINER</span><h3 style="margin-top:10px">Training Delivery</h3><p class="muted">Courses · Questionnaires · Performance · Library · Competency Matching</p></div><div class="card"><span class="pill blue">ADMIN</span><h3 style="margin-top:10px">Governance & Oversight</h3><p class="muted">Approvals · Roles · Courses · Analytics · Content · Reports</p></div></div><div class="card section"><h2>Access Control</h2><div class="tablewrap"><table><thead><tr><th>Module</th><th>Trainee</th><th>Trainer</th><th>Admin</th></tr></thead><tbody>${[["Profile","Own","Own","Manage"],["Competency","View / Update","Review","Manage Framework"],["Courses","Enroll","Create / Manage","Manage"],["Users","Own","Assigned","Manage"],["Analytics","Own progress","Trainee performance","Organization-wide"]].map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td></tr>`).join("")}</tbody></table></div></div>`);
if(state.page==="Course Management")return page("Course Management","Review, publish and manage organizational learning programmes.",`<div class="tablewrap"><table><thead><tr><th>Course</th><th>Trainer</th><th>Competencies</th><th>Enrollments</th><th>Status</th><th>Action</th></tr></thead><tbody>${courses.map((c,i)=>`<tr><td>${c.title}</td><td>${c.trainer}</td><td>${c.skills.join(", ")}</td><td>${c.learners}</td><td><span class="pill ${i===3?"amber":""}">${i===3?"Review":"Published"}</span></td><td><button class="btn small" onclick="toast('Course record opened')">Manage</button></td></tr>`).join("")}</tbody></table></div>`);
if(state.page==="Enrollment Monitoring")return monitoringPage("Enrollment Monitoring","Track course enrollment and participation.","Enrollments","4,782");
if(state.page==="Certification Monitoring")return monitoringPage("Certification Monitoring","Track certificates issued and verified.","Certificates Issued","2,936");
if(state.page==="Assessment Monitoring")return monitoringPage("Assessment Monitoring","Track assessment completion and outcomes.","Assessments Completed","8,412");
if(state.page==="Participation Statistics")return page("Participation Statistics","Organization-level training participation statistics.",`<div class="grid cards4">${kpi("Total Enrollments","4,782","+12%")}${kpi("Assessments Completed","8,412","+15%","amber")}${kpi("Active Trainees","1,086","+5.2%","teal")}${kpi("Average Performance","81%","+4%","green")}</div><div class="card section"><h2>Participation Trend</h2><div class="chart">${[38,51,48,65,58,78,86].map((v,i)=>`<div class="bar"><i style="height:${v}%"></i><span>${["Apr","May","Jun","Jul","Aug","Sep","Oct"][i]}</span></div>`).join("")}</div></div>`);
if(state.page==="Competency Framework")return page("Competency Framework","Maintain role requirements and competency definitions used by the competency engine.",`<div class="between"><div class="muted">Role requirements are compared against verified user competencies.</div><button class="btn primary" onclick="toast('New competency added')">Add Competency</button></div><div class="tablewrap section"><table><thead><tr><th>Role</th><th>Competency</th><th>Required Level</th><th>Evidence Type</th><th>Status</th></tr></thead><tbody><tr><td>Weather Forecaster</td><td>Radar Analysis</td><td>Advanced</td><td>Certificate / Trainer Review</td><td><span class="pill">Active</span></td></tr><tr><td>Weather Forecaster</td><td>Forecast Analysis</td><td>Advanced</td><td>Training / Assessment</td><td><span class="pill">Active</span></td></tr><tr><td>Climate Analyst</td><td>Data Analysis</td><td>Advanced</td><td>Certificate / Assessment</td><td><span class="pill">Active</span></td></tr></tbody></table></div>`);
if(state.page==="Competency Mapping")return page("Competency Mapping","Organization-level view of role requirements, skill gaps and trainer matches.",`<div class="arch"><div class="arch-col"><div class="arch-head">INPUTS</div><div class="arch-item">Role Requirements</div><div class="arch-item">Employee Profiles</div><div class="arch-item">Verified Evidence</div><div class="arch-item">Trainer Expertise</div></div><div class="arch-col"><div class="arch-head">COMPETENCY ENGINE</div><div class="arch-item">Credential Validation</div><div class="arch-item">Competency Mapping</div><div class="arch-item">Skill-Gap Analysis</div><div class="arch-item">Course Matching</div><div class="arch-item">Trainer Matching</div></div><div class="arch-col"><div class="arch-head">OUTPUTS</div><div class="arch-item">Skill Gap Insights</div><div class="arch-item">Recommended Courses</div><div class="arch-item">Verified Trainer Match</div></div></div><div class="tablewrap section"><table><thead><tr><th>Role</th><th>Competency Gap</th><th>Affected Trainees</th><th>Recommended Course</th><th>Matched Trainer</th></tr></thead><tbody><tr><td>Weather Forecaster</td><td>Radar Analysis</td><td>6</td><td>Radar Interpretation Fundamentals</td><td>Dr. Ananya Sharma · 94%</td></tr><tr><td>Climate Analyst</td><td>Data Analysis</td><td>8</td><td>Advanced Climate Data Analysis</td><td>Dr. R. Menon · 89%</td></tr></tbody></table></div>`);
if(state.page==="Announcements")return contentManagement("Announcements","Publish organization-wide announcements and notifications.","New Learning Content Available","New Radar Interpretation learning resources have been added to the Trainer Library.");
if(state.page==="Achievements")return contentManagement("Achievements","Publish institutional learning and competency achievements.","Competency Development Milestone","More than 1,000 competency records have been updated through learning and assessment.");
if(state.page==="Learning Content")return contentManagement("Learning Content","Manage new learning content published to the platform.","Radar Interpretation Guide","New study material and recorded lecture available for Weather Forecaster competency development.");
if(state.page==="Reports")return page("Reports","Organization-level reporting across training, assessments, certifications and participation.",`<div class="grid cards3"><div class="card"><h2>Training Activity Report</h2><p class="muted">Courses, enrollments, completion and participation.</p><button class="btn primary" onclick="toast('Training report prepared')">Generate Report</button></div><div class="card"><h2>Competency Gap Report</h2><p class="muted">Required vs current competencies and priority gaps.</p><button class="btn primary" onclick="toast('Competency report prepared')">Generate Report</button></div><div class="card"><h2>Certification Report</h2><p class="muted">Issued, pending and verified certifications.</p><button class="btn primary" onclick="toast('Certification report prepared')">Generate Report</button></div></div><div class="card section"><h2>Report Summary</h2><div class="tablewrap"><table><thead><tr><th>Metric</th><th>Current</th><th>Period</th><th>Status</th></tr></thead><tbody><tr><td>Course Completion</td><td>76%</td><td>Current</td><td><span class="pill">Healthy</span></td></tr><tr><td>Average Assessment</td><td>81%</td><td>Current</td><td><span class="pill">Tracked</span></td></tr><tr><td>Priority Skill Gaps</td><td>184</td><td>Current</td><td><span class="pill amber">Monitor</span></td></tr></tbody></table></div></div>`);
if(state.page==="Settings")return settings();
return page(state.page,"Administrative workspace.",`<div class="card"><h2>${state.page}</h2><p class="muted">Administrative control and monitoring area for the CAPACITY CONNECT prototype.</p></div>`);
}
function monitoringPage(title,sub,label,value){return page(title,sub,`<div class="grid cards3">${kpi(label,value,"Current period")}${kpi("Active Trainees","1,086","+5.2%","teal")}${kpi("Average Performance","81%","+4%","green")}</div><div class="card section"><h2>Monitoring Trend</h2><div class="chart">${[42,58,50,71,64,82,90].map((v,i)=>`<div class="bar"><i style="height:${v}%"></i><span>${["Apr","May","Jun","Jul","Aug","Sep","Oct"][i]}</span></div>`).join("")}</div></div>`)}
function contentManagement(title,sub,heading,text){return page(title,sub,`<div class="card"><div class="formgrid"><div class="field"><label>Title</label><input value="${heading}"></div><div class="field"><label>Status</label><select><option>Published</option><option>Draft</option></select></div><div class="field full"><label>Content</label><textarea>${text}</textarea></div></div><button class="btn primary" style="margin-top:15px" onclick="toast('${title} published successfully')">Publish</button></div><div class="grid cards3 section"><div class="card"><span class="pill">PUBLISHED</span><h3 style="margin-top:9px">${heading}</h3><p class="muted">${text}</p></div><div class="card"><h3>Homepage Visibility</h3><p class="muted">Visible to authenticated users and relevant public learning areas.</p><span class="pill blue">ENABLED</span></div><div class="card"><h3>Audit Trail</h3><p class="muted">Publisher: Admin — DEMO<br>Last updated: Today</p></div></div>`)}

function architecture(){
return page("System Architecture","Layered architecture proposed for the CAPACITY CONNECT implementation.",`<div class="arch"><div class="arch-col"><div class="arch-head">PRESENTATION LAYER</div><div class="arch-item">HTML · CSS · JavaScript</div><div class="arch-item">Responsive Web Interface</div><div class="arch-item">Trainee / Trainer / Admin UI</div></div><div class="arch-col"><div class="arch-head">APPLICATION LAYER</div><div class="arch-item">HTTPS / REST APIs</div><div class="arch-item">Flask REST API</div><div class="arch-item">Authentication + RBAC</div><div class="arch-item">Competency Engine</div><div class="arch-item">Assessment Engine</div></div><div class="arch-col"><div class="arch-head">DATA & STORAGE</div><div class="arch-item">MySQL — structured data</div><div class="arch-item">S3-compatible object storage</div><div class="arch-item">Recorded lectures</div><div class="arch-item">Presentations / study material</div></div></div><div class="card section"><h2>Competency Engine</h2><div class="workflow">${["User Inputs","Data Validation","Credential Validation","Competency Mapping","Skill-Gap Analysis","Course + Trainer Matching"].map((x,i)=>`<div class="flow">${i+1}. ${x}</div>`).join("")}</div><div class="notice" style="margin-top:16px"><b>Learning & Outcome:</b> Training → Subject-wise MCQ Assessment → Feedback → Certification → Updated Competency Profile → Re-evaluate Skill Gap → Continuous Development.</div></div><div class="card section"><h2>Security & Scalability</h2><div class="grid cards3"><div><b>Authentication</b><p class="muted">Authenticated access for users.</p></div><div><b>RBAC</b><p class="muted">Role-specific permissions for Trainee, Trainer and Admin.</p></div><div><b>Admin Approval</b><p class="muted">New accounts can require approval before activation.</p></div><div><b>Responsive</b><p class="muted">Cross-device web interface.</p></div><div><b>Modular</b><p class="muted">Separate competency, assessment and content components.</p></div><div><b>Scalable</b><p class="muted">Flask + MySQL + object storage can support extension across departments.</p></div></div></div>`)
}
// Persistent prototype state for cross-role interactions.
const APP_KEY = "capacity_connect_sih26075_state_v2";
let savedState = null;
try { savedState = localStorage.getItem(APP_KEY); } catch(e) { console.warn("Local storage unavailable; running in session-only mode.", e); }
if (savedState) {
  try { Object.assign(state, JSON.parse(savedState)); } catch(e) { console.warn("State restore failed", e); }
}
function persist(){
  try { localStorage.setItem(APP_KEY, JSON.stringify(state)); } catch(e) { console.warn("Local storage unavailable; state kept in memory.", e); }
}
function notify(message, targetRole=state.role){
  state.noticeCount = (state.noticeCount||0) + 1;
  state.notifications = state.notifications || [];
  state.notifications.unshift({message, role:targetRole, read:false, time:new Date().toLocaleString()});
  persist();
}
function setState(patch){ Object.assign(state, patch); persist(); render(); }
function render(){
if(!state.role){document.getElementById("app").innerHTML=landing();return}
let content="";
if(state.page==="Dashboard")content=dashboard();
else if(state.page==="My Profile")content=profile();
else if(state.role==="Trainee"){
const m={"Competency Assessment":competencyAssessment,"Competency Profile":competencyProfile,"Skill Gaps":skillGaps,"Recommended Learning":recommended,"Trainer Matching":trainerMatching,"Course Catalogue":catalogue,"My Learning":learning,"Learning Resources":resources,"Assessments":assessments,"Certificates":certificates,"Feedback":feedback,"Notifications":notifications,"Settings":settings,"System Architecture":architecture};
content=(m[state.page]||(()=>page(state.page,"Trainee workspace.",`<div class="card"><h2>${state.page}</h2></div>`)))();
}else if(state.role==="Trainer")content=state.page==="System Architecture"?architecture():trainerPage();
else content=state.page==="System Architecture"?architecture():adminPage();
document.getElementById("app").innerHTML=shell(content)
}
function toggleSide(){const s=document.querySelector(".sidebar");if(!s)return;const open=s.style.width && s.style.width!=="0px" && s.style.width!=="0";s.style.width=open?"0":"255px";s.style.padding=open?"0":"17px 12px"}
function approveUser(n){state.approvedUsers=state.approvedUsers||[];if(!state.approvedUsers.includes(n))state.approvedUsers.push(n);persist();notify(n+" account approved","Trainee");toast(n+" approved; role-based access activated");go("User Management")}
function restore(){const h=location.hash.replace(/^#/,"");if(!h||h==="landing"){state.role=null;render();return}if(h==="login"){loginView();return}const p=h.split("/").map(decodeURIComponent);if(p.length>=2&&["Trainee","Trainer","Admin"].includes(p[0])){state.role=p[0];state.page=p[1]||"Dashboard";persist();render()}}
window.addEventListener("hashchange",restore);
if(location.hash)restore();else render();
